name: weatherandairqualityapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  sqflite: ^2.0.0+4
  path_provider: ^2.0.3
  charts_flutter: 0.11.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  path: ^1.8.0
  mongo_dart: ^0.10.3
  google_maps_flutter: ^2.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  provider: ^6.1.2
  flutter_typeahead: ^3.1.1

dev_dependencies:
  dart_code_metrics: ^4.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
