// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```


class DefaultFirebaseOptions {

  // await Firebase.initializeApp(
  //     options: DefaultFirebaseOptions.currentPlatform,
  // );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutApwY0NtSOi8CwnuJe-3XtjX-gsLzQY',
    appId: '1:1071462398067:web:8c7b844ab34586b9f3d206',
    messagingSenderId: '1071462398067',
    projectId: 'weather-airquality',
    authDomain: 'weather-airquality.firebaseapp.com',
    storageBucket: 'weather-airquality.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuoaXUgYSb47hNwC-IPhUWdVEGQh5bZ8I',
    appId: '1:1071462398067:android:9488ecfbf6e25d11f3d206',
    messagingSenderId: '1071462398067',
    projectId: 'weather-airquality',
    storageBucket: 'weather-airquality.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC30AKALRBXIm-BFJ0iP-TFO6REpZKlP7w',
    appId: '1:1071462398067:ios:5c44ded6d576d3f0f3d206',
    messagingSenderId: '1071462398067',
    projectId: 'weather-airquality',
    storageBucket: 'weather-airquality.appspot.com',
    iosBundleId: 'com.example.weatherandairqualityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC30AKALRBXIm-BFJ0iP-TFO6REpZKlP7w',
    appId: '1:1071462398067:ios:5c44ded6d576d3f0f3d206',
    messagingSenderId: '1071462398067',
    projectId: 'weather-airquality',
    storageBucket: 'weather-airquality.appspot.com',
    iosBundleId: 'com.example.weatherandairqualityapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutApwY0NtSOi8CwnuJe-3XtjX-gsLzQY',
    appId: '1:1071462398067:web:ac9654c81491ffb5f3d206',
    messagingSenderId: '1071462398067',
    projectId: 'weather-airquality',
    authDomain: 'weather-airquality.firebaseapp.com',
    storageBucket: 'weather-airquality.appspot.com',
  );
}
